[CONFIG] setup deteKt hooks.

diff --git a/tools/config/pre-push b/tools/config/pre-push
--- a/tools/config/pre-push
+++ b/tools/config/pre-push
@@ -8,11 +8,13 @@ TXT_RED='\e[01;31m'
 TXT_RED2='\e[01;31m;47m'
 TXT_BLUE='\033[0;34m'
 
+TXT_ORANGE='\033[0;33m'
+
 BG_WHITE='\033[0;107m'
 COLOR_OFF='\033[0m'
 
 
-echo ""
+echo -e "${TXT_ORANGE}																	   "
 echo "⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠐⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀"
 echo "⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢰⡀⠀⠀⠀⠀⠀⠀⠀⡠⠌⠀⠀⠀⠀⠀⠀⠀⠀⣀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀"
 echo "⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⡞⣆⠀⠀⠀⠀⠀⠀⠒⡈⠆⠀⠀⠀⠀⠀⠀⣴⣉⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀"
@@ -31,8 +33,8 @@ echo "⠀⠀⠀⠩⣳⠬⣝⡒⠀⢸⣙⠆⡆⠸⣍⣳⣋⠶⠂⢨⠳⣥⢛⡔�
 echo "⣲⢒⢦⣀⣯⠲⣍⣳⠀⠸⣙⠶⣃⠴⣫⢽⡏⣖⠆⢸⠲⣍⠾⡁⠀⡵⢎⡳⠀⠀⠪⣕⢫⢦⠀⠀⠸⢬⡓⢧⡄⢀⢀⠀⠀⢱⢭⡚⡵⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⡲⠄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢱⣄⠀⠀⠀⠀⠀⠀⠀⠀⠈⠀⠁⠀"⠀
 echo "⠐⠫⢶⡡⢧⣛⡜⡦⠃⠀⠉⠚⠥⠛⠥⠃⢛⣬⣱⠐⢯⡜⢓⠀⠀⠙⠊⠑⠁⠀⠀⢎⡗⣎⠇⡀⠀⠑⠭⠳⠜⡭⠪⠁⠀⠘⡦⢫⢵⡋⠄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢄⢮⠱⠀⠀⠀⠀⠀⠘⢈⠀⠀⠀⠀⠀⢬⢣⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀"⠀⠀
 echo "⠀⠀⠀⠉⠀⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣠⢠⡝⡼⣘⠇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠙⠂⠙⠓⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢐⡏⡒⠁⠀⠀⠀⠀⠀⠌⢠⠀⠀⠀⠀⠀⠀⢣⢳⢀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀"
-echo "⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠉⠉⠈⠁⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠎⠀⠀⠀⠀⠀⠀⠀⠀⠊⠄⡆⠀⠀⠀⠀⠀⠀⠉⠆⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀"
-echo "⠀⣴⣶⣶⣶⢶⠶⠶⡶⠄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣀⣀⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠰⠠⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀"
+echo -e "${TXT_GREEN}"
+echo "⠀⣴⣶⣶⣶⢶⠶⠶⡶⠄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣀⣀⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀"
 echo "⢸⣿⣿⣿⣿⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠰⣿⣿⠇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀"
 echo "⢸⣿⣿⣿⣿⣶⣶⡶⠀⠀⣴⣦⡄⠀⠀⠀⣤⡠⠀⠀⠀⢀⣀⣀⠀⠀⠀⠀⠀⠀⠀⢀⣠⣤⣀⡀⠀⢀⣤⣤⣤⠀⠀⠀⠀⠀⠀⣀⣀⡀⠀⠀⠀⣀⣤⣀⣄⠀⠀⣀⣀⣀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣀⣀⣄⡀⠀⠀⠀⢀⣀⣤⣀⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀"
 echo "⢺⣿⣿⣿⣿⠁⠀⠀⠀⠀⠹⣿⣿⣧⣀⣾⣿⡟⠀⠀⠀⣿⣿⣿⣢⣴⣶⣤⡄⠀⣴⣿⣿⠀⣿⣿⠆⠈⣿⣿⣿⣦⣾⣿⠿⠓⢰⣿⣿⣷⠀⣰⣿⣿⠃⢹⣿⡆⠀⣿⣿⣿⡄⢀⣠⣤⣀⠀⠀⢠⣾⣿⡟⠛⠻⠁⠀⣾⣿⣿⠀⣿⣿⠀⠀⠀⠀⠀⠀⠀⠀⠀"⠀⠀
@@ -43,31 +45,66 @@ echo "⠀⠻⣿⣿⣿⣷⣶⣶⠦⠀⠀⠀⣿⡿⠉⠻⣿⣿⣧⠀⣸⣿⣿⣿�
 echo "⠀⠀⠈⠉⠉⠉⠉⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢽⣿⣿⣿⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠉⠋⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠉⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀"
 echo "⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⣿⣿⣿⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀"
 echo "⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠘⢿⠿⡿⠇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀"
-echo ""
-echo ""
-echo ""
-echo "[ktlint] Verificando formatação do código..."
+echo -e "${COLOR_OFF}"
 
+echo "[ktlint] Verificando formatação do código..."
 ./gradlew app:ktlintCheck --daemon
 
 status=$?
 
-if [ "$status" = 0 ] ; then
-    echo -e "${TXT_GREEN}✅ ${COLOR_OFF} Nenhum problema foi encontrado."
-    echo -e "ktlint ----------------------------------${TXT_GREEN}[SUCCESS]"
+echo ""
+
+echo "[DeteKt] Analisando o código..."
+./gradlew app:detekt --daemon
+
+statusdeteKt=$?
+
+get_ktlint_success() {
+    echo -e "ktlint --------------------------------------- ${TXT_GREEN}[SUCCESS]${COLOR_OFF}" 
+}
+
+get_ktlint_fail() {
+    echo -e "ktlint --------------------------------------- ${BG_WHITE}${TXT_RED}[FALHOU]${COLOR_OFF}"
     echo -e "${COLOR_OFF}" 
+    echo -e "Talvez você deva rodar o comando: ktlintFormat ->$TXT_BLUE ./gradlew app:ktlintFormat${COLOR_OFF}" 
+}
+
+get_detekt_success() {
+    echo -e "DeteKt --------------------------------------- ${TXT_GREEN}[SUCCESS]"
+}
+
+get_detekt_fail() {
+    echo -e "DeteKt --------------------------------------- ${BG_WHITE}${TXT_RED}[FALHOU]${COLOR_OFF}"
+    echo -e "Não se preocupa, dá uma olhadinha no relatório(pasta build): -> $TXT_BLUE detekt.html ${COLOR_OFF}"
+}
+
+if [[ "$status" == 0 ]] && [[ "$statusdeteKt" == 0 ]]; then
+    echo -e ""    
+    echo -e "${TXT_GREEN}✅ ${COLOR_OFF} Nenhum problema foi encontrado."
+    echo "$(get_ktlint_success)"
+    echo "$(get_detekt_success)"
     echo -e ""
 
     exit 0
 else
-
+    echo -e ""
     echo -e "${TXT_RED}☠️❌ ${COLOR_OFF} Eita.... Encontramos alguns problemas."
-    echo -e 1>&2 "Existes alguns pontos que precisam ser corrigidos !!!"
+    echo -e "Existes alguns pontos que precisam ser corrigidos !!!"
     echo -e ""
-    echo -e "ktlint --------------------------------------- ${BG_WHITE}${TXT_RED}[FALHOU]${COLOR_OFF}"
-    echo -e "${COLOR_OFF}"
-    echo -e "Talvez você deva rodar o comando: ktlintFormat ->$TXT_BLUE ./gradlew app:ktlintFormat" 
-    echo -e ""
+fi
+
+if [ "$status" == 1 ] ; then
+    echo "$(get_ktlint_fail)"
+
+    exit 1
+else
+   echo "$(get_ktlint_success)"
+fi
+
+if [ "$statusdeteKt" == 1 ] ; then
+    echo "$(get_detekt_fail)"  
 
     exit 1
 fi
+
+exit 0
